#!/usr/bin/env python3

import locale

try:
    locale.setlocale(locale.LC_ALL, 'fr_FR.UTF-8')
except:
    pass

import time
import signal
import piledmatrix
import schedule
import lockfile
import datetime
import urllib.request
import json


def display_date(matrix):
    matrix.add_message(datetime.date.today().strftime("%-d %B %Y").capitalize())


def display_weather(matrix):
    try:
        with urllib.request.urlopen("http://www.prevision-meteo.ch/services/json/pully") as url:
            data = json.loads(url.read().decode())
            weather = "Prévisons            "
            for i in range(5):
                if i > 0:
                    weather += "            "
                day_key = "fcst_day_{}".format(i)
                weather += data[day_key]['day_long']
                weather += "  "
                weather += data[day_key]['condition']
                weather += " {}°/{}°".format(data[day_key]
                                            ['tmin'], data[day_key]['tmax'])
            weather += "            "
            matrix.add_message(2*weather)
    except:
        pass


if __name__ == '__main__':

    m = piledmatrix.PiLedMatrix()
    m.start()

    schedule.every(20).seconds.do(display_date, matrix=m)
    schedule.every(120).seconds.do(display_weather, matrix=m)

    while True:
        schedule.run_pending()
        time.sleep(1)
