#!/usr/bin/env python3

import time
import signal
import piledmatrix
import schedule
import daemon
import lockfile
import datetime
import urllib.request
import json 

def display_date(matrix):
    matrix.AddMessage(datetime.date.today().strftime("%B %d, %Y"))

def display_weather(matrix):
    with urllib.request.urlopen("http://www.prevision-meteo.ch/services/json/pully") as url:
        data = json.loads(url.read().decode())
        weather = "Prévisons            "
        for i in range(5):
            if i > 0: 
                weather += "            "
            weather += data["fcst_day_{}".format(i)]['day_long']
            weather += "   "
            weather += data["fcst_day_{}".format(i)]['condition']
        weather += "            "        
        matrix.AddMessage(2*weather)

with daemon.DaemonContext():

    m = piledmatrix.PiLedMatrix()
    m.Start()

    schedule.every(20).seconds.do(display_date, matrix=m)
    schedule.every(120).seconds.do(display_weather, matrix=m)

    while True:
        schedule.run_pending()
        time.sleep(1)
